# Generated by Django 3.1.7 on 2021-03-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmreview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_year',
            field=models.CharField(default='0000', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='avg_imdb',
            field=models.FloatField(default='0000'),
        ),
    ]
