# Generated by Django 3.1.7 on 2021-03-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmreview', '0002_auto_20210326_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='avg_imdb',
            field=models.FloatField(),
        ),
    ]
