# Generated by Django 3.1.7 on 2021-03-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmreview', '0003_auto_20210326_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='sinopsis',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
