# Generated by Django 3.1.7 on 2021-03-26 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmreview', '0004_movie_sinopsis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='sinopsis',
            new_name='card_sinopsis',
        ),
    ]
