# Generated by Django 3.1.7 on 2021-03-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmreview', '0005_auto_20210326_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='card_sinopsis',
        ),
        migrations.AddField(
            model_name='movie',
            name='sinopsis',
            field=models.TextField(default=''),
        ),
    ]
