# Generated by Django 3.1.7 on 2021-03-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmreview', '0008_review_avaliation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='movie',
            name='sinopsis',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='avaliation',
            field=models.FloatField(default=6),
            preserve_default=False,
        ),
    ]
