# Generated by Django 3.1.7 on 2021-03-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmreview', '0008_auto_20210326_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='card_sinopsis',
        ),
        migrations.AddField(
            model_name='review',
            name='card_sinopsis',
            field=models.TextField(default='Sinopse não informada'),
        ),
    ]
