# Generated by Django 3.1.7 on 2021-03-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmreview', '0008_review_avaliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='sinopsis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='avaliation',
            field=models.FloatField(),
        ),
    ]
