# Generated by Django 3.1.7 on 2021-03-27 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmreview', '0009_auto_20210327_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_genre',
            new_name='genre',
        ),
    ]
