# Generated by Django 3.1.7 on 2021-03-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmreview', '0009_auto_20210326_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='card_sinopsis',
            field=models.TextField(),
        ),
    ]
