# Generated by Django 3.1.7 on 2021-03-27 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmreview', '0010_auto_20210327_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='sinopsis',
            new_name='synopsis',
        ),
    ]
