# Generated by Django 3.1.7 on 2021-03-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmreview', '0010_auto_20210326_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='card_sinopsis',
        ),
        migrations.AddField(
            model_name='movie',
            name='sinopsis',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
