# Generated by Django 3.1.7 on 2021-03-27 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmreview', '0011_auto_20210327_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='original_name',
            new_name='original_title',
        ),
    ]
