# Generated by Django 3.1.7 on 2021-04-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(db_index=True, max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=13, unique=True)),
                ('endereco', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'fornecedor',
            },
        ),
    ]
