# Generated by Django 3.1.7 on 2021-04-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0002_auto_20210402_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
